CREATE TABLE APP_USER
(
    ID                 SERIAL8 PRIMARY KEY,
    USERNAME            VARCHAR(60) UNIQUE NOT NULL,
    PASSWORD            VARCHAR(60)        NOT NULL,
    EMAIL               VARCHAR(60) UNIQUE NOT NULL,
    FIRST_NAME          VARCHAR(60)        NOT NULL,
    LAST_NAME           VARCHAR(60)        NOT NULL,
    PHONE_NUMBER        VARCHAR(9)         NOT NULL,
    GENDER              VARCHAR(6)         NOT NULL,
    IS_ACTIVE           BOOL               NOT NULL,
    ACTIVATION_CODE     VARCHAR(5)         NOT NULL,
    CREATED_DATE        TIMESTAMP,
    LAST_MODIFIED_BY    VARCHAR(60),
    LAST_MODIFIED_DATE  TIMESTAMP,
    MAIL_SENT_DATE      TIMESTAMP,
    MAIL_ACTIVATED_DATE TIMESTAMP
);

CREATE TABLE ROLE
(
    ID   SERIAL PRIMARY KEY,
    NAME VARCHAR(16)
);

CREATE TABLE INVITE
(
    ID   SERIAL PRIMARY KEY,
    BY_USER INTEGER NOT NULL,
    EVENT_ID INTEGER  NOT NULL,
    INVITED_USER INTEGER REFERENCES APP_USER (ID)
);

CREATE TABLE USER_ROLE
(
    USER_ID INTEGER REFERENCES APP_USER (ID),
    ROLE_ID INTEGER REFERENCES ROLE (ID)
);

CREATE TABLE FRIEND
(
    USER_ID   INTEGER REFERENCES APP_USER (ID),
    FRIEND_ID INTEGER REFERENCES APP_USER (ID),
    PRIMARY KEY (USER_ID, FRIEND_ID)
);

INSERT INTO ROLE
VALUES (1, 'ROLE_ADMIN');
INSERT INTO ROLE
VALUES (2, 'ROLE_USER');