CREATE TABLE EVENT
(
    ID                 SERIAL8 PRIMARY KEY,
    USER_ID            INTEGER NOT NULL,
    NAME               TEXT    NOT NULL,
    DESCRIPTION        TEXT    NOT NULL,
    DATE_TIME          TIMESTAMP,
    CREATED_DATE       DATE,
    LAST_MODIFIED_BY   VARCHAR(60),
    LAST_MODIFIED_DATE TIMESTAMP
);



CREATE TABLE EVENT_USER_IDS
(
    EVENT_ID INTEGER REFERENCES EVENT (ID),
    USER_ID INTEGER,
    PRIMARY KEY (EVENT_ID, USER_ID)
);


CREATE TABLE EVENT_PHOTO
(
    ID      SERIAL8 PRIMARY KEY,
    EVENT_ID INTEGER REFERENCES EVENT (ID) NOT NULL,
    URL     TEXT                         NOT NULL
);

