spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: facebook
feign:
  client:
    config:
      default:
        requestInterceptors: com.mic.chatservice.client.interceptor.AuthorizationRequestInterceptor
logging:
  config: classpath:log4j2.xml
  level:
    org:
      springframework:
        web: INFO
      hibernate: ERROR
    com:
      mic: DEBUG