spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:6552/facebook}
    username: "postgres"
    password: "secret"
    dbcp2:
      test-on-borrow: true
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      validation-query: SELECT 1
    tomcat:
      max-active: 15
      max-idle: 10
      max-wait: 8000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  cache:
    type: redis
  redis:
    host: ${SPRING_REDIS_HOST:localhost}
    port: 6379
    time-to-live: 3600
feign:
  client:
    config:
      default:
        requestInterceptors: com.mic.post.client.interceptor.AuthorizationRequestInterceptor
logging:
  config: classpath:log4j2.xml
  level:
    org:
      springframework:
        web: INFO
      hibernate: ERROR
    com:
      mic: DEBUG
cloud:
  aws:
    stack:
      auto: false
    region:
      static: eu-central-1
amazonProperties:
  region: eu-central-1
  bucketName: facebaak-photos
