zuul:
  routes:
    auth:
      sensitiveHeaders:
      path: /auth/**
      url: http://localhost:5000/
    post:
      sensitiveHeaders:
      path: /post/**
      url: http://localhost:5001/
    market:
      sensitiveHeaders:
      path: /market/**
      url: http://localhost:5006/
    event:
      sensitiveHeaders:
      path: /event/**
      url: http://localhost:5003/
eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
